version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - ./environment_variables/mysql.env
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql_db/data:/var/lib/mysql
      - ./mysql_db/log:/var/log/mysql
      - ./mysql_db/conf:/etc/mysql/conf.d
      - ./Generation/sql_scripts/mysql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - sourcesystem-net
  
  warehouse: 
    image: postgres:16
    container_name: warehouse
    ports: 
      - 5432:5432
    env_file:
      - ./environment_variables/postgres.env
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres_db:/var/lib/postgresql/data
      - ./Generation/sql_scripts/postgres:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - warehouse-net

volumes:
  mysql-volume:
  postgres-volume:

networks:
  warehouse-net:
    external: true
  sourcesystem-net:
    external: true
