name: learn-github-actions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_ec2:
    name: deploy_to_EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      # - name: Spin up test container networks
      #   run: make networks

      # - name: Run storages
      #   run: make storages
      

      - name: Deploy to staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "./"
          TARGET: "/home/ubuntu/test"
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: |
            make networks
            make storages
           